ifeq ($(CONFIG_ARCH_SUN50IW1P1),y)
-include $(obj)/de/lowlevel_sun50iw1/Makefile
endif

ifeq ($(CONFIG_ARCH_SUN8IW10),y)
-include $(obj)/de/lowlevel_sun8iw10/Makefile
endif

ifeq ($(CONFIG_ARCH_SUN8IW11),y)
-include $(obj)/de/lowlevel_v2x/Makefile
endif

ifeq ($(CONFIG_ARCH_SUN50IW2),y)
-include $(obj)/de/lowlevel_v2x/Makefile
endif
