# Copyright 2006 The Android Open Source Project

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif

ifdef WIFI_DRIVER_STATE_CTRL_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_STATE_CTRL_PARAM=\"$(WIFI_DRIVER_STATE_CTRL_PARAM)\"
endif
ifdef WIFI_DRIVER_STATE_ON
LOCAL_CFLAGS += -DWIFI_DRIVER_STATE_ON=\"$(WIFI_DRIVER_STATE_ON)\"
endif
ifdef WIFI_DRIVER_STATE_OFF
LOCAL_CFLAGS += -DWIFI_DRIVER_STATE_OFF=\"$(WIFI_DRIVER_STATE_OFF)\"
endif
# realtek usb wifi module
ifeq ($(BOARD_USR_WIFI), rtl8188eu)
LOCAL_CFLAGS += -DRTL_8188EU_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek sdio wifi+bt module
ifeq ($(BOARD_USR_WIFI), rtl8723bs)
LOCAL_CFLAGS += -DRTL_8723BS_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif
# realtek sdio wifi+bt module
ifeq ($(BOARD_USR_WIFI), rtl8723bs_vq0)
LOCAL_CFLAGS += -DRTL_8723BS_VQ0_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif
# realtek sdio wifi+bt module
ifeq ($(BOARD_USR_WIFI), rtl8723cs)
LOCAL_CFLAGS += -DRTL_8723CS_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif
# realtek sdio wifi module
ifeq ($(BOARD_USR_WIFI), rtl8189fs)
LOCAL_CFLAGS += -DRTL_8189FS_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif
#espressif sdio wifi module
ifeq ($(BOARD_USR_WIFI), esp8089)
LOCAL_CFLAGS += -DESPRESSIF_ESP8089_WIFI_USED
LOCAL_CFLAGS += -DESP_WIFI_VENDOR
endif
LOCAL_SRC_FILES += wifi/wifi.c

ifdef WPA_SUPPLICANT_VERSION
LOCAL_CFLAGS += -DLIBWPA_CLIENT_EXISTS
LOCAL_SHARED_LIBRARIES += libwpa_client
endif
LOCAL_SHARED_LIBRARIES += libnetutils
