language: java

# Skip "install" stage:
install: true

script: mvn -V -B clean verify

# Use container-based infrastructure:
sudo: false

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'
